name: Propagate Updates to Clients

on:
  push:
    branches:
      # Cambiar por main o las versiones especificas TAMBIEN cambiar en el run de steps
      - github

jobs:
  update-clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Aquí listas todos los repositorios que usan este submódulo
        repo: ['sergiodimier/principal-intcontinua']
    steps:
      - name: Checkout Cliente
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.GLOBAL_DISPATCH_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Actualizar Submódulo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git submodule update --init --recursive --remote
          
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-update submodules"
            # Al haber hecho el checkout con el PAT arriba, 
            # este push será reconocido como "manual" por GitHub
            # y disparará la Action en el repo COTA.
            git push origin main
          else
            echo "Sin cambios"
          fi