name: Propagate Updates to Clients

on:
  push:
    branches:
      # Cambiar por main o las versiones especificas TAMBIEN cambiar en el run de steps
      - github

jobs:
  update-clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Aquí listas todos los repositorios que usan este submódulo
        repo: ['sergiodimier/principal-intcontinua']
    steps:
      - name: Checkout Cliente
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.GLOBAL_DISPATCH_TOKEN }}
          submodules: true

      - name: Actualizar Submódulo
        run: |
          # 1. Configurar Usuario
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # 2. Inyectar Token para los submódulos
          git config --global url."https://x-token-auth:${{ secrets.GLOBAL_DISPATCH_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-token-auth:${{ secrets.GLOBAL_DISPATCH_TOKEN }}@github.com/".insteadOf "git@github.com:"

          # 3. Sincronizar e inicializar
          git submodule sync --recursive
          git submodule update --init --recursive

          # 4. Entrar al submódulo y forzar la rama
          cd submodules/submodules/integracion-continua
          git fetch origin github
          # Usamos -B para crear/resetear la rama local basada en la remota
          git checkout -B github origin/github
          cd ../../../

          # 5. Actualizar el puntero del repo padre
          git add submodules/submodules/integracion-continua
          
          # 6. Push si hay cambios
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto-update integracion-continua to latest on branch github"
            git push origin main
          else
            echo "Sin cambios para commitear"
          fi