name: Propagate Updates to Clients

on:
  push:
    branches:
      # Cambiar por main o las versiones especificas TAMBIEN cambiar en el run de steps
      - github

jobs:
  update-clients:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Aquí listas todos los repositorios que usan este submódulo
        repo: ['sergiodimier/principal-intcontinua']
    steps:
      - name: Checkout Cliente
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          token: ${{ secrets.GLOBAL_DISPATCH_TOKEN }}
          submodules: true

      - name: Actualizar Submódulo
        run: |
          # 1. Configurar Usuario
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # 2. Inyectar Token (Crucial para que el submódulo se deje leer)
          git config --global url."https://x-token-auth:${{ secrets.GLOBAL_DISPATCH_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-token-auth:${{ secrets.GLOBAL_DISPATCH_TOKEN }}@github.com/".insteadOf "git@github.com:"

          # 3. Sincronizar URLs (Por si cambió de SSH a HTTPS)
          git submodule sync --recursive

          # 4. Forzar el descubrimiento de ramas en el submódulo
          # Entramos a la ruta, traemos todo y volvemos a salir
          git submodule update --init --recursive
          cd submodules/submodules/integracion-continua
          git fetch origin github
          git checkout github
          cd ../../../

          # 5. Ahora sí, update remoto
          git submodule update --remote --recursive submodules/submodules/integracion-continua

          # 6. Push de los cambios
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-update integracion-continua to latest on branch github"
          git push origin main
